w5/w5d1/goal-app/config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  
  concern :commentable do
    resources :comments, only: [:new]
  end
    
  resources :users, concerns: :commentable
  resources :goals, concerns: :commentable
  resources :comments, except: [:new, :index]
  
  get ":commentable_id/comments/new", to: "comments#new", as: "new_comment"
  
  resource :session, only: [ :new, :create, :destroy ]
end

w5/w5d1/goal-app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

w5/w5d1/goal-app/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern
  
  included do
    has_many :comments, as: :commentable, dependent: :destroy
  end
end

w5/w5d1/goal-app/app/models/goal.rb
class Goal < ActiveRecord::Base
  include Commentable
  
  validates :user_id, :description, presence: true
  validates :private, :completed, inclusion: [true, false]
  
  after_initialize :default_to_public
  
  belongs_to :user

  def self.all_public
    self.where(private: false)
  end
  
  def default_to_public
    self.private ||= false
  end
  
end

w5/w5d1/goal-app/app/models/user.rb
class User < ActiveRecord::Base
  include Commentable
  
  validates :username,
    :password_digest,
    :session_token,
    presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  after_initialize :ensure_session_token
  
  has_many :goals, dependent: :destroy
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def self.find_by_credentials(username, password)
    user = self.find_by_username(username)
    return nil unless user
    user if user.is_password?(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def public_goals
    self.goals.where(private: false)
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end
  
  private
  
  attr_reader :password
  
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
  
end

w5/w5d1/goal-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
  
  def logged_in?
    !!current_user
  end
  
  def sign_in_user! user
    user.reset_session_token!
    session[:session_token] = user.session_token
  end
  
  def sign_out_user!
    current_user.reset_session_token! if current_user
    session[:session_token] = nil
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
  
end

w5/w5d1/goal-app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    
    if @comment.save
      flash[:notices] = [ "Comment created!" ]
      redirect_to @comment
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.commentable
  end
  
  def edit
    @comment = Comment.find(params[:id])
    render :edit
  end
  
  def new
    @comment = find_commentable.comments.new
    render :new
  end
  
  def show
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
    
    if @comment.update_attributes(comment_params)
      flash[:notices] = [ "Comment updated!" ]
      redirect_to @comment
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :edit
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

w5/w5d1/goal-app/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def create
    @goal = current_user.goals.new(goal_params)
    
    if @goal.save
      flash[:notices] = [ "Goal created!" ]
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end
  
  def destroy
    Goal.find(params[:id]).destroy
    flash[:notices] = [ "Goal destroyed!" ] 
    redirect_to current_user
  end
  
  def edit
    @goal = Goal.find(params[:id])
  end
  
  def index
    @goals = Goal.all_public
  end
  
  def new
    @goal = Goal.new
  end
  
  def show
    @goal = Goal.find(params[:id])
  end
  
  def update
    @goal = Goal.find(params[:id])
    
    if @goal.update_attributes(goal_params)
      flash[:notices] = [ "Goal updated!" ]
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end
  
  private
  
  def goal_params
    params.require(:goal).permit(:description, :private, :completed)
  end
end

w5/w5d1/goal-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_credentials(
      user_params[:username], user_params[:password]
    )
    
    if @user
      sign_in_user!(@user)
      flash[:notices] = [ "Welcome back, #{@user.username}!" ]
      redirect_to :root
    else
      flash.now[:errors] = ["Invalid login credentials!"]
      @user = User.new(user_params)
      render :new
    end
  end
  
  def destroy
    sign_out_user!
    redirect_to :root
  end
  
  def new
    if current_user
      redirect_to current_user
    else
      @user = User.new
      render :new
    end
  end
  
end

w5/w5d1/goal-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end
  
  def show
    @user = User.find(params[:id])
    @goals = @user == current_user ? @user.goals : @user.public_goals
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notices] = [ "#{@user.username} created!" ]
      sign_in_user! @user
      redirect_to :root
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      flash[:notices] = [ "#{@user.username} updated!" ]
      redirect_to :root
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end
  
  def destroy
  end
end

w5/w5d1/goal-app/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    html = "<input type='hidden' name='authenticity_token'"
    html += " value='#{form_authenticity_token}' >"
    html.html_safe
  end
end

w5/w5d1/goal-app/app/helpers/comments_helper.rb
module CommentsHelper
end

w5/w5d1/goal-app/app/helpers/goals_helper.rb
module GoalsHelper
end

w5/w5d1/goal-app/app/helpers/sessions_helper.rb
module SessionsHelper
end

w5/w5d1/goal-app/app/helpers/users_helper.rb
module UsersHelper
end

w5/w5d1/goal-app/app/views/comments/_form.html.erb
<% method = comment.persisted? ? "PATCH" : "POST" %>
<% action = comment.persisted? ? comment_url(comment) : comments_url %>
<% button = comment.persisted? ? "Update Comment"  : "Submit Comment" %>

<form action='<%= action %>' method="POST">
  <input type='hidden' name='_method' value='<%= method %>'>
  
  <%= auth_token %>
  
  <input type='hidden'
         name='comment[commentable_id]'
         value='<%= comment.commentable_id %>'>
         
  <input type='hidden'
         name='comment[commentable_type]'
         value='<%= comment.commentable_type %>'>

  <label for="comment_body">Comment Text</label>
  <textarea name="comment[body]"
            id="comment_body"
            ><%= comment.body %></textarea>
         
  <input type="submit" value="<%= button %>">
</form>

w5/w5d1/goal-app/app/views/comments/edit.html.erb
<h1><%= content_for(:title, "Edit Comment") %></h1>
<%= render 'form', comment: @comment %>

w5/w5d1/goal-app/app/views/comments/new.html.erb
<h1><%= content_for(:title, "New Comment") %></h1>
<%= render 'form', comment: @comment %>

w5/w5d1/goal-app/app/views/comments/show.html.erb
<h1><%= content_for(:title, "Comments#show") %></h1>

<%= @comment.body %>

<%= button_to "Edit Comment", edit_comment_url(@comment), method: :get %>
<%= button_to "Delete Comment", comment_url(@comment), method: :delete %>

w5/w5d1/goal-app/app/views/users/_form.html.erb
<% method ||= user.persisted? ? "PATCH" : "POST" %>
<% action ||= user.persisted? ? user_url(user) : users_url %>
<% button ||= user.persisted? ? "Update User"  : "Create User" %>

<form action='<%= action %>' method="POST">
  <input type='hidden' name='_method' value='<%= method %>'>
  
  <%= auth_token %>
  
  <label for="user_username">Username</label>
  <input type="text"
         name="user[username]"
         id="user_username"
         value="<%= @user.username %>">
         
  <label for="user_password">Password</label>
  <input type="password"
         name="user[password]"
         id="user_password">
         
  <input type="submit" value="<%= button %>">
</form>

w5/w5d1/goal-app/app/views/users/new.html.erb
<h1><%= content_for(:title, "New User") %></h1>
<%= render 'form', user: @user %>

w5/w5d1/goal-app/app/views/users/show.html.erb
<h1><%= content_for(:title, @user.username) %></h1>

<h3>Goals</h3>
<ul>
  <% @goals.each do |goal| %>
    <li><%= link_to goal.description, goal %> <%= "(Completed)" if goal.completed? %></li>
  <% end %>
</ul>

<% if @user == current_user %>
  <%= button_to "New Goal", new_goal_url, method: :get %>
<% end %>

<ul>
<% @user.comments.each do |comment| %>
  <li><%= link_to comment.body, comment_url(comment) %></li>
<% end %>
</ul>

<% if logged_in? %>
  <%= button_to "New Comment", new_user_comment_url(@user), method: :get %>
<% end %>